config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # List all tasks
  # root to: 'tasks#index'
  get 'tasks', to: 'tasks#index'
  # Show create form
  get 'tasks/new', to: 'tasks#new'
  # Create the task
  post 'tasks', to: 'tasks#create'
  # List one task
  get 'tasks/:id', to: 'tasks#show', as: :task
  # Show edit form
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # Update task
  patch 'tasks/:id', to: 'tasks#update'
  # Delete task
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end
end

private

def task_params
  params.require(:task).permit(:title, :details, :completed)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |task| %>
  <%= task.label :title %>
  <%= task.text_field :title %>
  <%= task.label :details %>
  <%= task.text_field :details %>
  <%= task.check_box :completed %>
  <%= task.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
  <% @tasks.each do |task|%>
    <li><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>

<%= link_to '+ Add a new task', tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @tasks %>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p>Title: <%= @task.title %><p>
<p>Details: <%= @task.details  %></p>
<p>Completed: <%= @task.completed  %> </p>

<%= link_to 'Back to list', tasks_path %>

<%= link_to 'Edit task', edit_task_path(@task) %>

<%# <%= link_to 'Delete task', delete_task_path, method: :delete> %>

<%= link_to "Delete task",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>